spring:
  application:
    name: servicestatistique


server:
  port: 8785

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

ribbon:
  eureka:
    enabled: true

