server:
  port: 8770

spring:
  application:
    name: authservice

zuul:
  sensitive-headers:
  prefix: /api/v1
  ignored-services: '*'
  host:
    max-total-connections: 1000
    max-per-route-connections: 1000
  routes:
    rdi-service:
      path: /rdi/**
      serviceId: rdiservice
      stripPrefix: false
    formation-service:
      path: /formation/**
      serviceId: serviceformation
      stripPrefix: false
    encadrement-service:
      path: /encadrement/**
      serviceId: serviceencadrement
      stripPrefix: false
    enseignant-service:
      path: /enseignant/**
      serviceId: serviceenseignant
      stripPrefix: false
    etudiant-service:
      path: /etudiant/**
      serviceId: serviceetudiant
      stripPrefix: false
    service-service:
      sensitiveHeaders:
      path: /service/**
      serviceId: servicesservice
      stripPrefix: false
    pedagogique-service:
      path: /pedagogique/**
      serviceId: pedagogiqueservice
      stripPrefix: false
    fileupload-service:
      path: /file/**
      serviceId: fileuploadservice
      stripPrefix: false
    calendrier-service:
      path: /calendrier/**
      serviceId: calendrierservice
      stripPrefix: false

ribbon:
  eureka:
    enabled: true
    
zuul:
  ribbon:
    ConnectTimeout: 10000000
    ReadTimeout: 10000000
